export const historikkMock = [
    {
        type: 'LAND',
        label: 'Norge',
        kvartalsvisSykefraværsprosent: [
            { prosent: 5.2, årstall: 2014, kvartal: 2, erMaskert: false },
            { prosent: 5.5, årstall: 2014, kvartal: 3, erMaskert: false },
            { prosent: 5.4, årstall: 2014, kvartal: 4, erMaskert: false },
            { prosent: 5.4, årstall: 2015, kvartal: 1, erMaskert: false },
            { prosent: 4.9, årstall: 2015, kvartal: 2, erMaskert: false },
            { prosent: 4.3, årstall: 2015, kvartal: 3, erMaskert: false },
            { prosent: 5.1, årstall: 2015, kvartal: 4, erMaskert: false },
            { prosent: 5.2, årstall: 2016, kvartal: 1, erMaskert: false },
            { prosent: 4.9, årstall: 2016, kvartal: 2, erMaskert: false },
            { prosent: 4.2, årstall: 2016, kvartal: 3, erMaskert: false },
            { prosent: 5.1, årstall: 2016, kvartal: 4, erMaskert: false },
            { prosent: 5.5, årstall: 2017, kvartal: 1, erMaskert: false },
            { prosent: 4.9, årstall: 2017, kvartal: 2, erMaskert: false },
            { prosent: 4.3, årstall: 2017, kvartal: 3, erMaskert: false },
            { prosent: 5.2, årstall: 2017, kvartal: 4, erMaskert: false },
            { prosent: 5.6, årstall: 2018, kvartal: 1, erMaskert: false },
            { prosent: 4.8, årstall: 2018, kvartal: 2, erMaskert: false },
            { prosent: 4.2, årstall: 2018, kvartal: 3, erMaskert: false },
            { prosent: 5.1, årstall: 2018, kvartal: 4, erMaskert: false },
            { prosent: 5.5, årstall: 2019, kvartal: 1, erMaskert: false },
            { prosent: 4.5, årstall: 2019, kvartal: 2, erMaskert: false },
        ],
    },
    {
        type: 'SEKTOR',
        label: 'Statlig forvaltning',
        kvartalsvisSykefraværsprosent: [
            { prosent: 4.9, årstall: 2014, kvartal: 2, erMaskert: false },
            { prosent: 5.2, årstall: 2014, kvartal: 3, erMaskert: false },
            { prosent: 5.0, årstall: 2014, kvartal: 4, erMaskert: false },
            { prosent: 5.1, årstall: 2015, kvartal: 1, erMaskert: false },
            { prosent: 4.6, årstall: 2015, kvartal: 2, erMaskert: false },
            { prosent: 4.0, årstall: 2015, kvartal: 3, erMaskert: false },
            { prosent: 4.8, årstall: 2015, kvartal: 4, erMaskert: false },
            { prosent: 5.0, årstall: 2016, kvartal: 1, erMaskert: false },
            { prosent: 4.6, årstall: 2016, kvartal: 2, erMaskert: false },
            { prosent: 4.0, årstall: 2016, kvartal: 3, erMaskert: false },
            { prosent: 4.8, årstall: 2016, kvartal: 4, erMaskert: false },
            { prosent: 5.1, årstall: 2017, kvartal: 1, erMaskert: false },
            { prosent: 4.6, årstall: 2017, kvartal: 2, erMaskert: false },
            { prosent: 4.1, årstall: 2017, kvartal: 3, erMaskert: false },
            { prosent: 5.0, årstall: 2017, kvartal: 4, erMaskert: false },
            { prosent: 5.3, årstall: 2018, kvartal: 1, erMaskert: false },
            { prosent: 4.5, årstall: 2018, kvartal: 2, erMaskert: false },
            { prosent: 4.0, årstall: 2018, kvartal: 3, erMaskert: false },
            { prosent: 4.9, årstall: 2018, kvartal: 4, erMaskert: false },
            { prosent: 5.2, årstall: 2019, kvartal: 1, erMaskert: false },
            { prosent: 5.2, årstall: 2019, kvartal: 2, erMaskert: false },
        ],
    },
    {
        type: 'NÆRING',
        label: 'Produksjon av nærings- og nytelsesmidler',
        kvartalsvisSykefraværsprosent: [
            { prosent: 5.6, årstall: 2017, kvartal: 1, erMaskert: false },
            { prosent: 5.1, årstall: 2017, kvartal: 2, erMaskert: false },
            { prosent: 4.4, årstall: 2017, kvartal: 3, erMaskert: false },
            { prosent: 5.4, årstall: 2017, kvartal: 4, erMaskert: false },
            { prosent: 5.7, årstall: 2018, kvartal: 1, erMaskert: false },
            { prosent: 5.0, årstall: 2018, kvartal: 2, erMaskert: false },
            { prosent: 4.4, årstall: 2018, kvartal: 3, erMaskert: false },
            { prosent: 5.4, årstall: 2018, kvartal: 4, erMaskert: false },
            { prosent: 5.6, årstall: 2019, kvartal: 1, erMaskert: false },
            { prosent: 5.1, årstall: 2019, kvartal: 2, erMaskert: false },
        ],
    },
    {
        type: 'VIRKSOMHET',
        label: 'NAV ARBEID OG YTELSER AVD OSLO',
        kvartalsvisSykefraværsprosent: [
            { prosent: 25.3, årstall: 2014, kvartal: 2, erMaskert: false },
            { prosent: 21.3, årstall: 2014, kvartal: 3, erMaskert: false },
            { prosent: 14.4, årstall: 2014, kvartal: 4, erMaskert: false },
            { prosent: 9.4, årstall: 2015, kvartal: 1, erMaskert: false },
            { prosent: 12.4, årstall: 2015, kvartal: 2, erMaskert: false },
            { prosent: 1.3, årstall: 2015, kvartal: 3, erMaskert: false },
            { prosent: 3.8, årstall: 2015, kvartal: 4, erMaskert: false },
            { prosent: 12.9, årstall: 2016, kvartal: 1, erMaskert: false },
            { prosent: 10.4, årstall: 2016, kvartal: 2, erMaskert: false },
            { prosent: 5.0, årstall: 2016, kvartal: 3, erMaskert: false },
            { prosent: 7.7, årstall: 2016, kvartal: 4, erMaskert: false },
            { prosent: 14.5, årstall: 2017, kvartal: 1, erMaskert: false },
            { prosent: 9.8, årstall: 2017, kvartal: 2, erMaskert: false },
            { prosent: 11.5, årstall: 2017, kvartal: 3, erMaskert: false },
            { prosent: 15.1, årstall: 2017, kvartal: 4, erMaskert: false },
            { prosent: 20.9, årstall: 2018, kvartal: 1, erMaskert: false },
            { prosent: 7.3, årstall: 2018, kvartal: 2, erMaskert: false },
            { prosent: 7.1, årstall: 2018, kvartal: 3, erMaskert: false },
            { prosent: 9.0, årstall: 2018, kvartal: 4, erMaskert: false },
            { prosent: 12.8, årstall: 2019, kvartal: 1, erMaskert: false },
            { prosent: 12.0, årstall: 2019, kvartal: 2, erMaskert: false },
        ],
    },
];
