apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: sykefravarsstatistikk
    namespace: default
    labels:
        team: {{team}}
spec:
    image: {{version}}
    team: {{team}}
    port: 3000
    vault:
        enabled: true
    ingresses:
        - https://arbeidsgiver.nav.no/sykefravarsstatistikk/
    liveness:
        path: /sykefravarsstatistikk/internal/isAlive
        initialDelay: 20
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 20
    env:
        - name: API_GATEWAY
          value: https://api-gw.oera.no
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
