const BASE_PATH = '/sykefravarsstatistikk';
const FRONTEND_API_PATH = BASE_PATH + '/api';
const SAMTALESTØTTE_MIKROFONTEND = 'samtalestotte-podlet';
const SAMTALESTØTTE_MIKROFRONTEND_PROXY_PATH = '/' + SAMTALESTØTTE_MIKROFONTEND;
const METRIKKER_API_PATH = BASE_PATH + '/metrikker';

module.exports = {
    BASE_PATH,
    FRONTEND_API_PATH,
    METRIKKER_API_PATH,
    SAMTALESTØTTE_MIKROFRONTEND_PROXY_PATH,
    SAMTALESTØTTE_MIKROFONTEND,
};
