apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: sykefravarsstatistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ version }}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: true
    ingresses:
        - https://arbeidsgiver-q.nav.no/sykefravarsstatistikk
        - https://arbeidsgiver.dev.nav.no/sykefravarsstatistikk
    liveness:
        path: /sykefravarsstatistikk/internal/isAlive
        initialDelay: 20
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 20
    env:
        - name: API_GATEWAY
          value: https://api-gw-q0.oera.no
        - name: NODE_ENV
          value: not-local
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=
    accessPolicy:
        outbound:
            external:
                - host: ia-tjenester-metrikker.dev.intern.nav.no

