apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: sykefravarsstatistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: true
    ingresses:
        - https://arbeidsgiver-gcp.nav.no/sykefravarsstatistikk
    liveness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    env:
        - name: API_GATEWAY
          value: https://api-gw-q0.oera.no
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LOGIN_URL
          value: https://loginservice.dev.nav.no/login?redirect=
    accessPolicy:
        outbound:
            external:
                - host: dekoratoren.dev.nav.no
