apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: sykefravarsstatistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: true
    ingresses:
        - https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk
    liveness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    env:
        - name: API_GATEWAY
          value: https://sykefravarsstatistikk-api.dev-fss-pub.nais.io
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LOGIN_URL
          value: https://loginservice.dev.nav.no/login?redirect=
        - name: NODE_ENV
          value: production
        - name: TOKENX_AUDIENCE
          value: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
        - name: APP_INGRESS
        - value: https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk
    tokenx:
        enabled: true
    idporten:
        enabled: true
        sidecar:
            enabled: true
    accessPolicy:
        outbound:
            rules:
                - application: sykefravarsstatistikk-api
                  namespace: arbeidsgiver
            external:
                - host: dekoratoren.dev.nav.no
                - host: sykefravarsstatistikk-api.dev-fss-pub.nais.io
                - host: loginservice.dev.nav.no
