apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: sykefravarsstatistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: true
    ingresses:
        - https://sykefravarsstatistikk.intern.dev.nav.no/sykefravarsstatistikk
    liveness:
        path: /sykefravarsstatistikk/internal/isAlive
        initialDelay: 10
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    prometheus:
        enabled: true
        path: /sykefravarsstatistikk/internal/metrics
    env:
        - name: BACKEND_API_BASE_URL
          value: https://sykefravarsstatistikk-api.dev-fss-pub.nais.io
        - name: IA_TJENESTER_METRIKKER_BASE_URL
          value: http://ia-tjenester-metrikker/ia-tjenester-metrikker
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: DEKORATOR_URL
          value: https://dekoratoren.ekstern.dev.nav.no
        - name: APP_INGRESS
          value: https://sykefravarsstatistikk.intern.dev.nav.no/sykefravarsstatistikk
        - name: SYKEFRAVARSSTATISTIKK_API_AUDIENCE
          value: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
        - name: IA_TJENESTER_METRIKKER_AUDIENCE
          value: "dev-gcp:arbeidsgiver:ia-tjenester-metrikker"
        - name: NOTIFIKASJON_API_AUDIENCE
          value: "dev-gcp:fager:notifikasjon-bruker-api"
        - name: MILJO
          value: dev-gcp
        - name: MIN_SIDE_ARBEIDSGIVER_URL
          value: https://min-side-arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver
        - name: FOREBYGGE_FRAVAR_URL
          value: https://forebygge-fravar.intern.dev.nav.no/forebygge-fravar
        - name: GRAFANA_AGENT_COLLECTOR_URL
          value: https://telemetry.ekstern.dev.nav.no/collect
    tokenx:
        enabled: true
    idporten:
        enabled: true
        sidecar:
            enabled: true
    accessPolicy:
        outbound:
            rules:
                - application: sykefravarsstatistikk-api
                  namespace: arbeidsgiver
                  cluster: dev-fss
                - application: notifikasjon-bruker-api
                  namespace: fager
                - application: ia-tjenester-metrikker
                  namespace: arbeidsgiver
                  cluster: dev-gcp
            external:
                - host: dekoratoren.ekstern.dev.nav.no
                - host: sykefravarsstatistikk-api.dev-fss-pub.nais.io
                - host: loginservice.dev.nav.no
