apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: sykefravarsstatistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: false
    ingresses:
        - https://arbeidsgiver.labs.nais.io/sykefravarsstatistikk
    tokenx:
        enabled: true
    idporten:
        enabled: true
        sidecar:
            enabled: true
    liveness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 10
    env:
        - name: NODE_ENV
          value: production
    accessPolicy:
        outbound:
            rules:
                - application: sykefravarsstatistikk-api
                  namespace: arbeidsgiver
            external:
                - host: dekoratoren.dev.nav.no
                - host: fakedings.dev-gcp.nais.io
