apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: sykefravarsstatistikk
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ image }}
    team: arbeidsgiver
    port: 3000
    vault:
        enabled: true
    ingresses:
        - https://arbeidsgiver.nav.no/sykefravarsstatistikk
    liveness:
        path: /sykefravarsstatistikk/internal/isAlive
        initialDelay: 20
    readiness:
        path: /sykefravarsstatistikk/internal/isReady
        initialDelay: 20
    prometheus:
        enabled: true
        path: /sykefravarsstatistikk/metrics
    env:
        - name: BACKEND_API_BASE_URL
          value: https://sykefravarsstatistikk-api.prod-fss-pub.nais.io
        - name: IA_TJENESTER_METRIKKER_BASE_URL
          value: https://arbeidsgiver.nav.no/ia-tjenester-metrikker
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: LOGIN_URL
          value: https://loginservice.nav.no/login?redirect=
        - name: DEKORATOR_URL
          value: https://www.nav.no/dekoratoren
        - name: APP_INGRESS
          value: https://arbeidsgiver.nav.no/sykefravarsstatistikk
        - name: SYKEFRAVARSSTATISTIKK_API_AUDIENCE
          value: "prod-fss:arbeidsgiver:sykefravarsstatistikk-api"
        - name: IA_TJENESTER_METRIKKER_AUDIENCE
          value: "prod-gcp:arbeidsgiver:ia-tjenester-metrikker"
        - name: NOTIFIKASJON_API_AUDIENCE
          value: "prod-gcp:fager:notifikasjon-bruker-api"
        - name: MILJO
          value: prod-gcp
        - name: MIN_SIDE_ARBEIDSGIVER_URL
          value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver
        - name: FOREBYGGE_FRAVAR_URL
          value: https://arbeidsgiver.nav.no/forebygge-fravar
    tokenx:
        enabled: true
    idporten:
        enabled: true
        sidecar:
            enabled: true
    accessPolicy:
        outbound:
            rules:
                - application: sykefravarsstatistikk-api
                  namespace: arbeidsgiver
                  cluster: prod-fss
                - application: notifikasjon-bruker-api
                  namespace: fager
                - application: ia-tjenester-metrikker
                  namespace: arbeidsgiver
                  cluster: prod-gcp
            external:
                - host: dekoratoren.nav.no
                - host: sykefravarsstatistikk-api.prod-fss-pub.nais.io
                - host: loginservice.nav.no
